on:
  issues:
    types: [labeled]

jobs:
  move-issue:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Run Python script
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"
        echo "ISSUE_NUMBER=${{github.event.issue.number}}" >> "$GITHUB_ENV"
        python ./move_issue.py $GITHUB_TOKEN $ISSUE_NUMBER



